### ISSUE TITLE
Node >=20 support

### ISSUE THREAD

**Issue by peterbe** [aklinker1/publish-browser-extension#16]
It says you have to have Node 18 (and npm 8):
https://github.com/aklinker1/publish-browser-extension/blob/42041ef0e2aa9a3278ef0a0552b9e823b159d5b4/package.json#L5-L8
Pardon my ignorance for not knowing *why* but consider this issue a **feature request** to support >=20 :)

I noticed it when testing [WXT](https://wxt.dev/guide/installation.html) as I saw:

```
❯ npx wxt@latest init ghdocser
Need to install the following packages:
wxt@0.16.4
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'publish-browser-extension@2.1.1',
npm WARN EBADENGINE   required: { node: '18', pnpm: '8' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }

WXT 0.16.4
```

**Comment by aklinker1** [comment]
Looks like it's an upstream issue with `publish-browser-extension`. I'll update it.

**Comment by aklinker1** [comment]
Good catch, that's accidental. I'll fix it

**Comment by aklinker1** [comment]
Released WXT update: https://github.com/wxt-dev/wxt/releases/tag/v0.16.5
