### ISSUE TITLE
Specifically report missing configs

### ISSUE THREAD

**Issue by hyoban** [aklinker1/publish-browser-extension#18]
https://github.com/aklinker1/publish-browser-extension/blob/dbdd0d24c3aa74ff03e8fb9e1f0479a536337172/src/config.ts#L80-L84

Now it just throws an error, it might be better to pinpoint the missing config.

I am willing to submit a pull request for this change.

**Comment by aklinker1** [comment]
Yeah, I guess zod errors don't tell you much... Ok, if you want to submit a PR, feel please do!
