### ISSUE TITLE
401 unauthorized "Signature has expired." error with Firefox Add-ons

### ISSUE THREAD

**Issue by uncenter** [aklinker1/publish-browser-extension#21]
I've been recently getting this `Error:  [POST] "https://addons.mozilla.org/api/v5/addons/addon/***/versions/": 401 Unauthorized` error when attempting to publish to the Firefox Add-ons store, with the response containing ` "detail": "Signature has expired."` - see https://github.com/catppuccin/github-file-explorer-icons/actions/runs/9531192442/job/26271894539, https://github.com/catppuccin/github-file-explorer-icons/actions/runs/9367734622. The first time I got the error was after updating WXT from `0.17.3` to `0.18.4` (https://github.com/catppuccin/github-file-explorer-icons/pull/55, https://github.com/catppuccin/github-file-explorer-icons/pull/59). After reading through the changelog for those releases, the only possibly connected change seems to be https://github.com/wxt-dev/wxt/pull/501, though even that is a stretch. Between the last successful release and the failed one no credentials were changed, though one of the failed releases today was after ensuring those were updated. This might be an issue for WXT itself but seeing as it is only publishing related I thought asking here first might be better.

**Comment by aklinker1** [comment]
Gonna close this since it's a file size problem. Will open another issue focused on throwing a useful error.
